name: Linting
# Linting tools use `pyproject.toml` and `setup.cfg` for config.

on:
  - pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r admin/requirements/requirements-dev.txt

      - name: isort
        run: inv lint isort
      - name: black
        run: inv lint black
      - name: flake8
        run: inv lint flake8
      - name: mypy
        run: inv lint mypy
