# Note on running admin tasks that would use `typer-invoke`:
#   pip install typer-invoke
#   inv some task
#
# Since this project *is* `typer-invoke`, we run it directly:
#   python -m src.typer_invoke.invoke some task

name: Linting
# Linting tools use `pyproject.toml` for config.

on:
  - pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create virtual environment
        run: uv venv

      # Use code from this project to run the admin tasks
      - name: Install requirements
        run: |
          uv run python -m src.typer_invoke.invoke pip install dev

      - name: Linting
        run: uv run  python -m src.typer_invoke.invoke lint all --check
